service: hello-serverless

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  memorySize: 128
  timeout: 10


functions:
  hello:
    handler: handler.hello
    events:
      - http:
         path: test/version1
         method: post
         cors: true