service: hello-serverless

provider:
  name: aws
  runtime: nodejs12.x


functions:
  hello:
    handler: handler.hello
    events:
      - http:
         path: test/version1
         method: post
         cors: true